version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=lei_drupal_test
      - MARIADB_DATABASE=lei_drupal_test
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  drupal:
    image: docker.io/bitnami/drupal:9
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=lei_drupal_test
      - DRUPAL_DATABASE_NAME=lei_drupal_test
      - DRUPAL_SITE_NAME=LEITest
      - DRUPAL_USERNAME=user
      - DRUPAL_PASSWORD=pass
      # - DRUPAL_PASSWORD=bitnami
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'drupal_data:/bitnami/drupal'
    #  - './custom:/drupal-test-lei_drupal_data/_data/modules/custom'
    # command: bash -c "sudo apt install git -y; git clone git@github.com:kaarele/lei-drupal-test"
    # command:
    #     - bash
    #     - -c
    #     - >
    #       apt update;
    #       apt install git -y;
    #       git clone git@github.com:kaarele/lei-drupal-test.git;
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
